### ISSUE TITLE
Searching the arm64 build of docker-gen

### ISSUE THREAD

**Issue by grosbedos** [buchdag/multiarch-letsencrypt-nginx-proxy#2]
Sorry, you can delete this issue...

**Comment by buchdag** [comment]
As you probably found, because [the PR for arm64 alpine builds](https://github.com/jwilder/docker-gen/pull/272) still hasn't been merged to `jwilder/docker-gen`, I still have to get the binaries from my own fork. To be honest I've pretty much lost hope that it will be merged one day and included in an upstream release.
